# NumPy (Numerical Python)

## Overview
- fundamental package for all scientific computing
- Numpy uses fixed types and is hence much faster than lists
 - faster to read less bytes of memory
 - no type checking when iterating through objects
 - contiguous memory

## Applicaltions of Numpy?
- Mathematics (MATLAB "replacement")
- Plotting (Matplotlib)
- Backend (e.g. Pandas, Matplotlib)
- Machine Learning

## Table of content
- (i) The basics
- (ii) Initializing different types of arrays
- (iii) Mathematics
- (iv) Statistics
- (v) Reorganizing arrays

## (i) The basics

In [1]:
import numpy as np

In [5]:
# simple array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
# two dimensional array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
# Get dimensions
b.ndim

2

In [9]:
# Get shape
b.shape

(2, 3)

In [10]:
# Get type
b.dtype

dtype('float64')

In [11]:
# Define datatype
a = np.array([1, 2, 3], dtype = 'int32')
a

array([1, 2, 3])

---

In [12]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [13]:
# Get specific element
c[1,2]

10

In [14]:
# Get specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get specific column
c[:, 2]

array([ 3, 10])

In [16]:
# Advanced selecting
# startindex : endindex : stepsize
c[0, 1:6:2]

array([2, 4, 6])

In [17]:
c[0, 1:-1:2]

array([2, 4, 6])

In [19]:
# Assigning values 
c[1, 5] = 20
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [22]:
# Indexing with a list
a[[0, 2]]

array([1, 3])

## (ii) Initializing different types of arrays

In [23]:
# 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
# Any other number
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [28]:
# Random decimal numbers
np.random.rand(4,2)

array([[2.26026605e-01, 5.70119237e-04],
       [1.96280154e-01, 5.40472765e-01],
       [2.42590390e-01, 3.47534083e-01],
       [4.82871929e-01, 8.14227404e-01]])

In [29]:
# Random integer values (from 0 to 6)
np.random.randint(7, size=(3,3))

array([[6, 3, 3],
       [2, 3, 3],
       [3, 0, 4]])

In [30]:
# Identity matrix
np.identity(3)  # or np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
# Arange
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [70]:
# Arange with starting point
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [72]:
# Arange with stepsize
np.arange(30,100,5)

array([30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [31]:
# ! Be careful when copying arrays
a = np.array([1,2,3])
b = a
b[0] = 100
a[0]

100

In [32]:
# Solution: 
b = a.copy()

## (iii) Mathematics

In [41]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [42]:
a = a+2
a

array([3, 4, 5, 6])

In [47]:
a = np.array([1,2,3,4])
a = a + 2
a

array([3, 4, 5, 6])

In [48]:
a = np.array([1,2,3,4])
a = a * 2
a

array([2, 4, 6, 8])

In [49]:
a = np.array([1,2,3,4])
a = a / 2
a

array([0.5, 1. , 1.5, 2. ])

In [50]:
a = np.array([1,2,3,4])
b = np.array([1, 0, 1, 0])
a+b

array([2, 2, 4, 4])

In [51]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
# Matrix multiplier
a = np.ones((2,3))
b = np.full((3,2), 2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [78]:
# Dot product -- is the sum of the products of elements
a = np.array([1,2,3,4])
b = np.array([1, 0, 1, 0])
np.dot(a,b)

4

In [54]:
# Matrix determinant -- matrix must be square
c = np.identity(3)
np.linalg.det(c)

1.0

... much more:
- trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse

## (iv) Statistics

In [56]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# Minimum
np.min(stats)

1

In [58]:
# Maximum
np.max(stats)

6

In [59]:
# Minimum over axis
np.min(stats, axis=1)

array([1, 4])

In [60]:
np.min(stats, axis=0)

array([1, 2, 3])

In [61]:
# Sum 
np.sum(stats)

21

## (v) Reorganizing arrays

In [62]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
# Reshape
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [65]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [73]:
# Transpose
before.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [67]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [68]:
# Horizontal stack
np.hstack([v1, v2, v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

In [74]:
# Combining arrays
a = np.array([1,2,3,4])
b = np.array([3,3,3])
np.concatenate((a,b))

array([1, 2, 3, 4, 3, 3, 3])

## Miscellaneous

In [ ]:
# Load data from text file
filedata = np.genfromtxt('data.txt', delimiter=',')

In [ ]:
# Convert type --no inplace change happening
filedata = filedata.astype('int32')

In [ ]:
# Shuffle DataFrame
np.random.shuffle(df.values)

In [ ]:
# Plot image from numpy array
# image 300 x 300
plt.imshow(image, cmap='Greys_r') # if no colors are defined

# image 300 x 300 x 3
plt.imshow(image)  # x 3 means rgb colorsetting

In [ ]:
# Convert PNG/JPG images to numpy array
import imageio
im = imageio.imread(URL)
im_np = np.asarray(im)
print(im_np.shape)  # 180x260x3